# Accounts Service Gateway Config
spring:
  cloud:
    gateway:
      routes:
        - id: accounts
          uri: lb://accounts-service
          predicates:
            - Path=/accounts/**
        - id: orders
          uri: lb://orders-service
          predicates:
            - Path=/orders/**
        - id: products
          uri: lb://products-service
          predicates:
            - Path=/products/**
        - id: shipments
          uri: lb://shipments-service
          predicates:
            - Path=/shipments/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  application:
    name: gateway-service

server:
  port: 8000

eureka:
  instance:
    hostname: gateway-service
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_INSTANCE_HOSTNAME:localhost}:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
  health:
    ratelimiters:
      enabled: true
    circuitbreakers:
      enabled: true
