# Accounts Service Gateway Config
spring:
    application:
      name: gateway-service
    cloud:
      gateway:
        routes:
          - id: accounts
            uri: http://${host.docker.internal:localhost}:8001/
            predicates:
              - Path=/accounts/**
          - id: orders
            uri: http://${host.docker.internal:localhost}:8004/
            predicates:
              - Path=/orders/**
          - id: products
            uri: http://${host.docker.internal:localhost}:8002/
            predicates:
              - Path=/products/**
          - id: shipments
            uri: http://${host.docker.internal:localhost}:8003/
            predicates:
              - Path=/shipments/**
        discovery:
          locator:
            enabled: true

server:
  port: 8000


eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:8761/eureka/
  instance:
    statusPageUrl: https://${eureka.instance.hostname:localhost}:${server.port}/actuator/info
    healthCheckUrl: https://${eureka.instance.hostname:localhost}:${server.port}/health
    homePageUrl: https://${eureka.instance.hostname:localhost}:${server.port}/
    appname: gateway-service

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    circuit-breakers:
      enabled: true
    rate limiters:
      enabled: true
